class BarManager:

    def show_tables(self):
        ...

    def show_waiter(self):
        ...

    def show_total_effectiveness_per_waiter(self, id_waiter: int):
        ...

    def show_total_customer_per_Waiter(self, id_waiter: int):
        ...

    def show_total_tip_per_waiter(self, id_waiter: int):
        ...

    def update_waiter(self):
        ...

    def generate_order(self):
        ...

    def finish_order(self):
        ...
